site_name: Navi Bluetooth Testing Suite

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search:
      lang: en
  - gen-files:
      scripts:
        - docs/gen_pages.py
  - mkdocstrings:
      handlers:
        python:
          paths: [navi]
          options:
            show_root_heading: true
