[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "navi"
description = "Android Bluetooth Navi Testing Suite"
version = "0.1.0"
authors = [
    { name = "Google", email = "pixel-bluetooth-testing-dev@google.com" },
]
requires-python = ">=3.12"
dependencies = [
    "bumble==0.0.234",
    "mobly",
    "typing_extensions",
    "pydub",
    "absl-py",
    "snippet-uiautomator",
    "numpy",
    "mobly-android-partner-tools >= 1.1.1",
    "audioop-lts; python_version >= '3.13'",
]

[dependency-groups]
dev = ["mypy == 1.15.0", "ruff == 0.12.4"]
doc = [
    "mkdocs >= 1.6.0",
    "mkdocs-material >= 9.6",
    "mkdocstrings[python] >= 0.27.0",
    "mkdocs-gen-files >= 0.5.0",
]

[project.scripts]
navi_venti = "navi.tests.main:run_venti"
navi_smoke = "navi.tests.main:run_smoke"
navi_firmware = "navi.tests.main:run_firmware"
navi_all = "navi.tests.main:run_all"

[tool.mypy]
follow_untyped_imports = true
disable_error_code = ["method-assign"]


[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = ["E731", "F401", "E741"]
