# Build and check the python package
name: Python build and check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.12", "3.13"]
      fail-fast: false

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        persist-credentials: false

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
      with:
        version: "0.8.0"
        python-version: ${{ matrix.python-version }}

    - name: Set up venv
      run: uv venv

    - name: Install dependencies
      run: |
        uv sync --all-groups

    # On Windows, there are a lot of issues related to UTF-8
    - name: Set environment variables
      if: runner.os == 'Windows'
      run: |
        chcp 65001 #set code page to utf-8
        echo "PYTHONUTF8=1" >> $env:GITHUB_ENV

    - name: Check
      run: |
        uv run mypy navi
        uv run ruff check

    - name: Get Test List
      run: |
        uv run navi_all -l
