name: Publish docs via GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"

      - name: Set up Python
        run: uv python install

      - name: Set up venv
        run: uv venv

      - name: Install requirements
        run: uv pip install ".[doc]"

      - name: Deploy 🚀
        run: uv run mkdocs gh-deploy --force
